package com.SistemaDeEmpleados.Views;

import com.SistemaDeEmpleados.Controllers.AppColors;
import com.SistemaDeEmpleados.Controllers.DashboardController;
import com.SistemaDeEmpleados.Controllers.Icons;
import com.SistemaDeEmpleados.Controllers.WindowPositionController;
import javax.swing.JLabel;

// TODO import ComponentMaintainer.CM_Views;
// TODO import Classes.Assistance;
/**
 * @author Kris
 */
public class Dashboard extends javax.swing.JFrame {

    public Dashboard() {

        initComponents();

        setLocationRelativeTo(null);

        new DashboardController().showButtons(btn_employees, btn_departments,
                btn_employeeSearch, btn_employeeRegistration);

        new Icons().setDashboardIcons(new JLabel[]{
            icon_employeeRegistration,
            icon_employeeSearch,
            icon_employees,
            icon_departments,
            icon_reports,
            icon_projects,
            icon_profile});

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        btn_close = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        btn_employees = new javax.swing.JPanel();
        txt_btn_employees = new javax.swing.JLabel();
        icon_employees = new javax.swing.JLabel();
        btn_departments = new javax.swing.JPanel();
        txt_btn_departments = new javax.swing.JLabel();
        icon_departments = new javax.swing.JLabel();
        btn_reports = new javax.swing.JPanel();
        txt_btn_reports = new javax.swing.JLabel();
        icon_reports = new javax.swing.JLabel();
        btn_projects = new javax.swing.JPanel();
        txt_btn_projects = new javax.swing.JLabel();
        icon_projects = new javax.swing.JLabel();
        btn_profile = new javax.swing.JPanel();
        txt_btn_profile = new javax.swing.JLabel();
        icon_profile = new javax.swing.JLabel();
        btn_logout = new javax.swing.JPanel();
        txt_btn_logout = new javax.swing.JLabel();
        herobar = new javax.swing.JPanel();
        btn_employeeSearch = new javax.swing.JPanel();
        txt_btn_employeeSearch = new javax.swing.JLabel();
        icon_employeeSearch = new javax.swing.JLabel();
        btn_employeeRegistration = new javax.swing.JPanel();
        txt_btn_employeeRegistration = new javax.swing.JLabel();
        icon_employeeRegistration = new javax.swing.JLabel();
        displaycontent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de empleados - Dashboard");
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setName("dashboard"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 255, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setMaximumSize(new java.awt.Dimension(720, 35));
        header.setPreferredSize(new java.awt.Dimension(720, 35));

        btn_close.setBackground(AppColors.CloseButton());
        btn_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_close.setMinimumSize(new java.awt.Dimension(25, 25));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(38, 13, 52));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");

        javax.swing.GroupLayout btn_closeLayout = new javax.swing.GroupLayout(btn_close);
        btn_close.setLayout(btn_closeLayout);
        btn_closeLayout.setHorizontalGroup(
            btn_closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_closeLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btn_closeLayout.setVerticalGroup(
            btn_closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        content.setBackground(AppColors.Background());
        content.setPreferredSize(new java.awt.Dimension(1280, 685));

        sidebar.setBackground(ColorScheme.SetColor.EGGSHELL);
        sidebar.setPreferredSize(new java.awt.Dimension(200, 685));

        btn_employees.setBackground(ColorScheme.SetColor.DESERT_SAND);
        btn_employees.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_employees.setPreferredSize(new java.awt.Dimension(150, 35));

        txt_btn_employees.setFont(new java.awt.Font("Bungee", 0, 12)); // NOI18N
        txt_btn_employees.setForeground(ColorScheme.SetColor.UMBER);
        txt_btn_employees.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_btn_employees.setText("Empleados");

        icon_employees.setText("jLabel3");
        icon_employees.setPreferredSize(new java.awt.Dimension(24, 24));

        javax.swing.GroupLayout btn_employeesLayout = new javax.swing.GroupLayout(btn_employees);
        btn_employees.setLayout(btn_employeesLayout);
        btn_employeesLayout.setHorizontalGroup(
            btn_employeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_employeesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_employees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_btn_employees, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        btn_employeesLayout.setVerticalGroup(
            btn_employeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_employeesLayout.createSequentialGroup()
                .addGroup(btn_employeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(icon_employees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_btn_employees))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_departments.setBackground(ColorScheme.SetColor.DESERT_SAND);
        btn_departments.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_departments.setPreferredSize(new java.awt.Dimension(150, 35));

        txt_btn_departments.setFont(new java.awt.Font("Bungee", 0, 12)); // NOI18N
        txt_btn_departments.setForeground(ColorScheme.SetColor.UMBER);
        txt_btn_departments.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_btn_departments.setText("Departamentos");

        icon_departments.setText("jLabel3");
        icon_departments.setPreferredSize(new java.awt.Dimension(24, 24));

        javax.swing.GroupLayout btn_departmentsLayout = new javax.swing.GroupLayout(btn_departments);
        btn_departments.setLayout(btn_departmentsLayout);
        btn_departmentsLayout.setHorizontalGroup(
            btn_departmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_departmentsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_departments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_btn_departments, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        btn_departmentsLayout.setVerticalGroup(
            btn_departmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_departmentsLayout.createSequentialGroup()
                .addGroup(btn_departmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(icon_departments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_btn_departments))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_reports.setBackground(ColorScheme.SetColor.DESERT_SAND);
        btn_reports.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_reports.setPreferredSize(new java.awt.Dimension(150, 35));

        txt_btn_reports.setFont(new java.awt.Font("Bungee", 0, 12)); // NOI18N
        txt_btn_reports.setForeground(ColorScheme.SetColor.UMBER);
        txt_btn_reports.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_btn_reports.setText("Reportes");

        icon_reports.setText("jLabel3");
        icon_reports.setPreferredSize(new java.awt.Dimension(24, 24));

        javax.swing.GroupLayout btn_reportsLayout = new javax.swing.GroupLayout(btn_reports);
        btn_reports.setLayout(btn_reportsLayout);
        btn_reportsLayout.setHorizontalGroup(
            btn_reportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_reportsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_reports, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_btn_reports, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        btn_reportsLayout.setVerticalGroup(
            btn_reportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_reportsLayout.createSequentialGroup()
                .addGroup(btn_reportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(icon_reports, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_btn_reports))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_projects.setBackground(ColorScheme.SetColor.DESERT_SAND);
        btn_projects.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_projects.setPreferredSize(new java.awt.Dimension(150, 35));

        txt_btn_projects.setFont(new java.awt.Font("Bungee", 0, 12)); // NOI18N
        txt_btn_projects.setForeground(ColorScheme.SetColor.UMBER);
        txt_btn_projects.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_btn_projects.setText("Proyectos");

        icon_projects.setText("jLabel3");
        icon_projects.setPreferredSize(new java.awt.Dimension(24, 24));

        javax.swing.GroupLayout btn_projectsLayout = new javax.swing.GroupLayout(btn_projects);
        btn_projects.setLayout(btn_projectsLayout);
        btn_projectsLayout.setHorizontalGroup(
            btn_projectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_projectsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_projects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_btn_projects, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        btn_projectsLayout.setVerticalGroup(
            btn_projectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_projectsLayout.createSequentialGroup()
                .addGroup(btn_projectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(icon_projects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_btn_projects))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_profile.setBackground(ColorScheme.SetColor.DESERT_SAND);
        btn_profile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_profile.setPreferredSize(new java.awt.Dimension(150, 35));

        txt_btn_profile.setFont(new java.awt.Font("Bungee", 0, 12)); // NOI18N
        txt_btn_profile.setForeground(ColorScheme.SetColor.UMBER);
        txt_btn_profile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_btn_profile.setText("Perfil");

        icon_profile.setText("jLabel3");
        icon_profile.setPreferredSize(new java.awt.Dimension(24, 24));

        javax.swing.GroupLayout btn_profileLayout = new javax.swing.GroupLayout(btn_profile);
        btn_profile.setLayout(btn_profileLayout);
        btn_profileLayout.setHorizontalGroup(
            btn_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_profileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_profile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_btn_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        btn_profileLayout.setVerticalGroup(
            btn_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_profileLayout.createSequentialGroup()
                .addGroup(btn_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(icon_profile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_btn_profile))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_logout.setBackground(ColorScheme.SetColor.DESERT_SAND);
        btn_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_logout.setPreferredSize(new java.awt.Dimension(150, 35));

        txt_btn_logout.setFont(new java.awt.Font("Bungee", 0, 12)); // NOI18N
        txt_btn_logout.setForeground(ColorScheme.SetColor.UMBER);
        txt_btn_logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_btn_logout.setText("Cerrar sesión");

        javax.swing.GroupLayout btn_logoutLayout = new javax.swing.GroupLayout(btn_logout);
        btn_logout.setLayout(btn_logoutLayout);
        btn_logoutLayout.setHorizontalGroup(
            btn_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_btn_logout, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        btn_logoutLayout.setVerticalGroup(
            btn_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_btn_logout, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_employees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_departments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_reports, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_projects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_profile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(btn_employees, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_departments, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_reports, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_projects, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 349, Short.MAX_VALUE)
                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        herobar.setBackground(ColorScheme.SetColor.EGGSHELL);
        herobar.setPreferredSize(new java.awt.Dimension(60, 45));

        btn_employeeSearch.setBackground(ColorScheme.SetColor.DESERT_SAND);
        btn_employeeSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_employeeSearch.setPreferredSize(new java.awt.Dimension(150, 35));

        txt_btn_employeeSearch.setFont(new java.awt.Font("Bungee", 0, 12)); // NOI18N
        txt_btn_employeeSearch.setForeground(ColorScheme.SetColor.UMBER);
        txt_btn_employeeSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_btn_employeeSearch.setText("Buscar empleados");

        icon_employeeSearch.setText("jLabel3");
        icon_employeeSearch.setPreferredSize(new java.awt.Dimension(24, 24));

        javax.swing.GroupLayout btn_employeeSearchLayout = new javax.swing.GroupLayout(btn_employeeSearch);
        btn_employeeSearch.setLayout(btn_employeeSearchLayout);
        btn_employeeSearchLayout.setHorizontalGroup(
            btn_employeeSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_employeeSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_employeeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_btn_employeeSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addContainerGap())
        );
        btn_employeeSearchLayout.setVerticalGroup(
            btn_employeeSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_employeeSearchLayout.createSequentialGroup()
                .addGroup(btn_employeeSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(icon_employeeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_btn_employeeSearch))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_employeeRegistration.setBackground(ColorScheme.SetColor.DESERT_SAND);
        btn_employeeRegistration.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_employeeRegistration.setPreferredSize(new java.awt.Dimension(150, 35));

        txt_btn_employeeRegistration.setFont(new java.awt.Font("Bungee", 0, 12)); // NOI18N
        txt_btn_employeeRegistration.setForeground(ColorScheme.SetColor.UMBER);
        txt_btn_employeeRegistration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_btn_employeeRegistration.setText("Registrar empleados");

        icon_employeeRegistration.setText("jLabel3");
        icon_employeeRegistration.setPreferredSize(new java.awt.Dimension(24, 24));

        javax.swing.GroupLayout btn_employeeRegistrationLayout = new javax.swing.GroupLayout(btn_employeeRegistration);
        btn_employeeRegistration.setLayout(btn_employeeRegistrationLayout);
        btn_employeeRegistrationLayout.setHorizontalGroup(
            btn_employeeRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_employeeRegistrationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_employeeRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_btn_employeeRegistration, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addContainerGap())
        );
        btn_employeeRegistrationLayout.setVerticalGroup(
            btn_employeeRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_employeeRegistrationLayout.createSequentialGroup()
                .addGroup(btn_employeeRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(icon_employeeRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_btn_employeeRegistration))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout herobarLayout = new javax.swing.GroupLayout(herobar);
        herobar.setLayout(herobarLayout);
        herobarLayout.setHorizontalGroup(
            herobarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(herobarLayout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(btn_employeeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(625, Short.MAX_VALUE))
            .addGroup(herobarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(herobarLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(btn_employeeRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(847, Short.MAX_VALUE)))
        );
        herobarLayout.setVerticalGroup(
            herobarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, herobarLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(btn_employeeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(herobarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, herobarLayout.createSequentialGroup()
                    .addContainerGap(16, Short.MAX_VALUE)
                    .addComponent(btn_employeeRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        displaycontent.setBackground(AppColors.Background());
        displaycontent.setPreferredSize(new java.awt.Dimension(100, 520));

        javax.swing.GroupLayout displaycontentLayout = new javax.swing.GroupLayout(displaycontent);
        displaycontent.setLayout(displaycontentLayout);
        displaycontentLayout.setHorizontalGroup(
            displaycontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        displaycontentLayout.setVerticalGroup(
            displaycontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(herobar, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
                    .addComponent(displaycontent, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contentLayout.createSequentialGroup()
                        .addComponent(herobar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(displaycontent, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE))
                    .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                    .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            Dashboard dashboard = new Dashboard();

            dashboard.setVisible(true);

            new WindowPositionController(
                    dashboard,
                    dashboard.header,
                    dashboard.btn_close);

            new DashboardController().buttonsEventListener(
                    dashboard.btn_employees,
                    dashboard.btn_employeeSearch,
                    dashboard.btn_employeeRegistration,
                    dashboard.btn_departments,
                    dashboard.btn_reports,
                    dashboard.btn_projects,
                    dashboard.btn_profile,
                    dashboard.btn_logout);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_close;
    private javax.swing.JPanel btn_departments;
    private javax.swing.JPanel btn_employeeRegistration;
    private javax.swing.JPanel btn_employeeSearch;
    private javax.swing.JPanel btn_employees;
    private javax.swing.JPanel btn_logout;
    private javax.swing.JPanel btn_profile;
    private javax.swing.JPanel btn_projects;
    private javax.swing.JPanel btn_reports;
    private javax.swing.JPanel content;
    private javax.swing.JPanel displaycontent;
    private javax.swing.JPanel header;
    private javax.swing.JPanel herobar;
    private javax.swing.JLabel icon_departments;
    private javax.swing.JLabel icon_employeeRegistration;
    private javax.swing.JLabel icon_employeeSearch;
    private javax.swing.JLabel icon_employees;
    private javax.swing.JLabel icon_profile;
    private javax.swing.JLabel icon_projects;
    private javax.swing.JLabel icon_reports;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel sidebar;
    private javax.swing.JLabel txt_btn_departments;
    private javax.swing.JLabel txt_btn_employeeRegistration;
    private javax.swing.JLabel txt_btn_employeeSearch;
    private javax.swing.JLabel txt_btn_employees;
    private javax.swing.JLabel txt_btn_logout;
    private javax.swing.JLabel txt_btn_profile;
    private javax.swing.JLabel txt_btn_projects;
    private javax.swing.JLabel txt_btn_reports;
    // End of variables declaration//GEN-END:variables
}
