package com.SistemaDeEmpleados.Views;

import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.HashSet;

/**
 * @author Kris
 */
public final class EmployeeSearchModule extends javax.swing.JPanel {

    /**
     * Creates new form EmployeeRegister
     */
    public EmployeeSearchModule() {
        initComponents();
        FindEmployeeCreateModel();
    }
// TODO repair list employees method
//    private void listEmployees(Connection dbConnection) {
//        final String listQuery = "SELECT usr_name, usr_position, usr_salary, dept_name FROM users, departments WHERE usr_assignedDepartment = dept_id";
//
//        Object O[] = null;
//
//        try (PreparedStatement pstmt = dbConnection.prepareStatement(listQuery)) {
//            try (ResultSet rs = pstmt.executeQuery()) {
//                int i = 0;
//                while (rs.next()) {
//                    model.addRow(O);
//                    model.setValueAt(rs.getString("usr_name"), i, 0);
//                    model.setValueAt(rs.getString("dept_name"), i, 1);
//                    model.setValueAt(rs.getString("usr_position"), i, 2);
//                    model.setValueAt(rs.getString("usr_salary"), i, 3);
//                    i++;
//                }
//            }
//        } catch (SQLException e) {
//            System.err.println("Error al listar los empleados: " + e);
//        }
//
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EmployeeRegisterContainer = new javax.swing.JPanel();
        lbl_moduleName = new javax.swing.JLabel();
        btn_filter = new javax.swing.JPanel();
        txt_btn_filter = new javax.swing.JLabel();
        filterby_salary = new javax.swing.JComboBox<>();
        filterby_position = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_FindEmployee = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(1080, 640));
        setMinimumSize(new java.awt.Dimension(1080, 640));
        setPreferredSize(new java.awt.Dimension(1080, 640));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EmployeeRegisterContainer.setBackground(ColorScheme.SetColor.COSMIC_LATE);
        EmployeeRegisterContainer.setMaximumSize(new java.awt.Dimension(1080, 640));
        EmployeeRegisterContainer.setMinimumSize(new java.awt.Dimension(1080, 640));
        EmployeeRegisterContainer.setPreferredSize(new java.awt.Dimension(1080, 640));

        lbl_moduleName.setFont(new java.awt.Font("Bungee", 0, 24)); // NOI18N
        lbl_moduleName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_moduleName.setText("Busqueda de empleados");

        btn_filter.setBackground(ColorScheme.SetColor.DESERT_SAND);
        btn_filter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_filter.setPreferredSize(new java.awt.Dimension(150, 35));

        txt_btn_filter.setFont(new java.awt.Font("Bungee", 0, 12)); // NOI18N
        txt_btn_filter.setForeground(ColorScheme.SetColor.UMBER);
        txt_btn_filter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_btn_filter.setText("Filtrar");
        txt_btn_filter.setPreferredSize(new java.awt.Dimension(70, 30));

        javax.swing.GroupLayout btn_filterLayout = new javax.swing.GroupLayout(btn_filter);
        btn_filter.setLayout(btn_filterLayout);
        btn_filterLayout.setHorizontalGroup(
            btn_filterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_filterLayout.createSequentialGroup()
                .addComponent(txt_btn_filter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        btn_filterLayout.setVerticalGroup(
            btn_filterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_btn_filter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        filterby_salary.setBackground(ColorScheme.SetColor.EGGSHELL);
        filterby_salary.setForeground(ColorScheme.SetColor.DESERT_SAND);
        filterby_salary.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "salary:" }));
        filterby_salary.setBorder(null);
        filterby_salary.setPreferredSize(new java.awt.Dimension(120, 30));

        filterby_position.setBackground(ColorScheme.SetColor.DESERT_SAND);
        filterby_position.setForeground(ColorScheme.SetColor.DESERT_SAND);
        filterby_position.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "position:" }));
        filterby_position.setBorder(null);
        filterby_position.setPreferredSize(new java.awt.Dimension(120, 30));

        tbl_FindEmployee.setBackground(ColorScheme.SetColor.DESERT_SAND);
        tbl_FindEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbl_FindEmployee.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tbl_FindEmployee.setForeground(ColorScheme.SetColor.UMBER);
        tbl_FindEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Departamento", "Cargo", "Asistencia promedio", "Tareas completadas", "Salario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_FindEmployee.setGridColor(new java.awt.Color(0, 0, 0));
        tbl_FindEmployee.setSelectionBackground(ColorScheme.SetColor.EGGSHELL);
        jScrollPane1.setViewportView(tbl_FindEmployee);

        javax.swing.GroupLayout EmployeeRegisterContainerLayout = new javax.swing.GroupLayout(EmployeeRegisterContainer);
        EmployeeRegisterContainer.setLayout(EmployeeRegisterContainerLayout);
        EmployeeRegisterContainerLayout.setHorizontalGroup(
            EmployeeRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeRegisterContainerLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(EmployeeRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE)
                    .addComponent(lbl_moduleName))
                .addGap(135, 135, 135))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmployeeRegisterContainerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(filterby_position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(filterby_salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(btn_filter, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        EmployeeRegisterContainerLayout.setVerticalGroup(
            EmployeeRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeRegisterContainerLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbl_moduleName)
                .addGroup(EmployeeRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmployeeRegisterContainerLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(EmployeeRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(filterby_salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(filterby_position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(EmployeeRegisterContainerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_filter, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        add(EmployeeRegisterContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

//    TODO repair sortItems method
//    private String[] SortItems(Connection dbConnection, String queryText, String placeholder) {
//        final String sortQuery = "SELECT " + queryText + " FROM users";
//
//        ArrayList<String> sortedList = new ArrayList<>();
//        HashSet<String> tempSort = new HashSet<>();
//
//        sortedList.add(placeholder);
//
//        try (PreparedStatement pstmt = dbConnection.prepareStatement(sortQuery)) {
//            try (ResultSet rs = pstmt.executeQuery()) {
//                while (rs.next()) {
//                    String element = rs.getString(queryText);
//                    if (!tempSort.contains(element)) {
//                        tempSort.add(element);
//                        sortedList.add(element);
//                    }
//                }
//            }
//        } catch (SQLException sqle) {
//            System.err.println("Error al ordenar los elementos: " + sqle);
//        }
//
//        return sortedList.toArray(String[]::new);
//    }

    DefaultTableModel model;

    public void FindEmployeeCreateModel() {
        try {
            model = (new DefaultTableModel(null, new String[]{
                "Nombre y Apellidos", "Departamento", "Cargo", "Salario"}) {
                @SuppressWarnings("rawtypes")
                Class[] types = new Class[]{
                    java.lang.String.class, java.lang.String.class, java.lang.String.class,
                    java.lang.String.class};
                boolean[] canEdit = new boolean[]{
                    false, false, false, false};

                @SuppressWarnings({
                    "rawtypes", "unchecked"})
                @Override
                public Class getColumnClass(int columnIndex) {
                    return types[columnIndex];
                }

                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            });
            tbl_FindEmployee.setModel(model);
        } catch (Exception e) {
            System.err.println("Error no se pudo crear la tabla" + e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EmployeeRegisterContainer;
    private javax.swing.JPanel btn_filter;
    private javax.swing.JComboBox<String> filterby_position;
    private javax.swing.JComboBox<String> filterby_salary;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_moduleName;
    private javax.swing.JTable tbl_FindEmployee;
    private javax.swing.JLabel txt_btn_filter;
    // End of variables declaration//GEN-END:variables
}
