package com.SistemaDeEmpleados.Views;

import javax.swing.*;

import com.SistemaDeEmpleados.Controllers.Fonts.Fonts;
import com.SistemaDeEmpleados.Controllers.WindowPositionController;
import com.SistemaDeEmpleados.Controllers.LoginController;
import com.SistemaDeEmpleados.Controllers.Icons;

/**
 * @author Kris
 */
public class LoginView extends javax.swing.JFrame {

    private final Fonts customFont;

    public LoginView() {
        this.customFont = new Fonts();
        initComponents();
        setLocationRelativeTo(null);
        new Icons().setLoginIcons(new JLabel[]{ico_user, ico_password, ico_citybg});

        new WindowPositionController(this,
                this.header,
                this.btn_close);

        new LoginController(
                this,
                this.txt_username,
                this.txt_password,
                this.loginContainer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //public static DatabaseConection dbc = new DatabaseConection();
    // public static User actualSession = new User();
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        usernameContainer = new javax.swing.JPanel();
        txt_username = new javax.swing.JTextField();
        ico_user = new javax.swing.JLabel();
        passwordContainer = new javax.swing.JPanel();
        txt_password = new javax.swing.JPasswordField();
        ico_password = new javax.swing.JLabel();
        loginContainer = new javax.swing.JPanel();
        lbl_login = new javax.swing.JLabel();
        lbl_appName = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        btn_close = new javax.swing.JPanel();
        btn_close_label = new javax.swing.JLabel();
        bgHero = new javax.swing.JPanel();
        ico_citybg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(255, 255, 255));

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setPreferredSize(new java.awt.Dimension(520, 445));

        usernameContainer.setBackground(com.SistemaDeEmpleados.Controllers.AppColors.Button());
        usernameContainer.setPreferredSize(new java.awt.Dimension(280, 30));

        txt_username.setBackground(com.SistemaDeEmpleados.Controllers.AppColors.Button());
        txt_username.setFont(customFont.CustomFont("INTER", "PLAIN", 12)
        );
        txt_username.setForeground(com.SistemaDeEmpleados.Controllers.AppColors.Text());
        txt_username.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_username.setText("Usuario:");
        txt_username.setBorder(null);
        txt_username.setPreferredSize(new java.awt.Dimension(245, 30));

        ico_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ico_user.setMaximumSize(new java.awt.Dimension(25, 25));
        ico_user.setMinimumSize(new java.awt.Dimension(25, 25));
        ico_user.setPreferredSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout usernameContainerLayout = new javax.swing.GroupLayout(usernameContainer);
        usernameContainer.setLayout(usernameContainerLayout);
        usernameContainerLayout.setHorizontalGroup(
            usernameContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usernameContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ico_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        usernameContainerLayout.setVerticalGroup(
            usernameContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usernameContainerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(usernameContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ico_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        passwordContainer.setBackground(com.SistemaDeEmpleados.Controllers.AppColors.Button());
        passwordContainer.setPreferredSize(new java.awt.Dimension(280, 35));

        txt_password.setBackground(com.SistemaDeEmpleados.Controllers.AppColors.Button());
        txt_password.setFont(customFont.CustomFont("INTER", "PLAIN", 12)
        );
        txt_password.setForeground(com.SistemaDeEmpleados.Controllers.AppColors.Text());
        txt_password.setText("12345678");
        txt_password.setBorder(null);
        txt_password.setPreferredSize(new java.awt.Dimension(245, 35));

        ico_password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ico_password.setPreferredSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout passwordContainerLayout = new javax.swing.GroupLayout(passwordContainer);
        passwordContainer.setLayout(passwordContainerLayout);
        passwordContainerLayout.setHorizontalGroup(
            passwordContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, passwordContainerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ico_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        passwordContainerLayout.setVerticalGroup(
            passwordContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, passwordContainerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(passwordContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ico_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        loginContainer.setBackground(com.SistemaDeEmpleados.Controllers.AppColors.Button());
        loginContainer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginContainer.setMaximumSize(new java.awt.Dimension(280, 30));
        loginContainer.setMinimumSize(new java.awt.Dimension(280, 30));

        lbl_login.setFont(customFont.CustomFont("LILITAONE", "PLAIN", 12)
        );
        lbl_login.setForeground(com.SistemaDeEmpleados.Controllers.AppColors.Text());
        lbl_login.setText("Iniciar Sesion");

        javax.swing.GroupLayout loginContainerLayout = new javax.swing.GroupLayout(loginContainer);
        loginContainer.setLayout(loginContainerLayout);
        loginContainerLayout.setHorizontalGroup(
            loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginContainerLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(lbl_login)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        loginContainerLayout.setVerticalGroup(
            loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginContainerLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(lbl_login)
                .addContainerGap())
        );

        lbl_appName.setFont(customFont.CustomFont("LILITAONE", "PLAIN", 24)
        );
        lbl_appName.setForeground(com.SistemaDeEmpleados.Controllers.AppColors.Text());
        lbl_appName.setText("Sistema de empleados");

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addComponent(usernameContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                            .addComponent(jSeparator2)
                            .addComponent(loginContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordContainer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(lbl_appName)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lbl_appName)
                .addGap(18, 18, 18)
                .addComponent(usernameContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(passwordContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(loginContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setPreferredSize(new java.awt.Dimension(720, 35));

        btn_close.setBackground(com.SistemaDeEmpleados.Controllers.AppColors.CloseButton());
        btn_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_close.setMinimumSize(new java.awt.Dimension(25, 25));

        btn_close_label.setBackground(new java.awt.Color(255, 255, 255));
        btn_close_label.setForeground(new java.awt.Color(38, 13, 52));
        btn_close_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_close_label.setText("X");

        javax.swing.GroupLayout btn_closeLayout = new javax.swing.GroupLayout(btn_close);
        btn_close.setLayout(btn_closeLayout);
        btn_closeLayout.setHorizontalGroup(
            btn_closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_closeLayout.createSequentialGroup()
                .addComponent(btn_close_label, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btn_closeLayout.setVerticalGroup(
            btn_closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_close_label, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(689, Short.MAX_VALUE)
                .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bgHero.setName(""); // NOI18N
        bgHero.setPreferredSize(new java.awt.Dimension(200, 450));

        ico_citybg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ico_citybg.setText("citybg");

        javax.swing.GroupLayout bgHeroLayout = new javax.swing.GroupLayout(bgHero);
        bgHero.setLayout(bgHeroLayout);
        bgHeroLayout.setHorizontalGroup(
            bgHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ico_citybg, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        bgHeroLayout.setVerticalGroup(
            bgHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ico_citybg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(bgHero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bgHero, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                LoginView login = new LoginView();

                login.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel bgHero;
    public javax.swing.JPanel btn_close;
    public javax.swing.JLabel btn_close_label;
    private javax.swing.JPanel content;
    private javax.swing.JPanel header;
    private javax.swing.JLabel ico_citybg;
    private javax.swing.JLabel ico_password;
    private javax.swing.JLabel ico_user;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_appName;
    public javax.swing.JLabel lbl_login;
    public javax.swing.JPanel loginContainer;
    private javax.swing.JPanel passwordContainer;
    public javax.swing.JPasswordField txt_password;
    public javax.swing.JTextField txt_username;
    private javax.swing.JPanel usernameContainer;
    // End of variables declaration//GEN-END:variables
}
